#!/usr/bin/env python3
import argparse
import sys


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog='go2web',
        description='HTTP over TCP sockets: fetch URLs and search the web.',
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('-u', '--url', help='Make an HTTP request to URL and print human-readable response')
    group.add_argument('-s', '--search', nargs='+', help='Search term (single word or multiple words)')
    group.add_argument('-v', '--version', action='store_true', help='Show version')
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.version:
        print('go2web 1.0.0')
        return 0

    if args.url:
        print('URL mode is not implemented yet.', file=sys.stderr)
        return 1

    if args.search:
        print('Search mode is not implemented yet.', file=sys.stderr)
        return 1

    parser.print_help()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
